"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import useScrollAnimation from "@/hooks/useScrollAnimation";

interface InsightArticle {
    id: number;
    title: string;
    date: string;
    description: string;
    href: string;
}

const articles: InsightArticle[] = [
    {
        id: 1,
        title: "ReActEdge Partners with Anduril on Army's Next Generation Command and Control Initiative",
        date: "FEBRUARY 23, 2026",
        description: "OPERATIONAL INTELLIGENCE PLATFORM INTEGRATES WITH LATTICE MESH TO DELIVER NEAR REAL-TIME VEHICLE HEALTH DATA FOR ENHANCED MISSION READINESS",
        href: "/insights/1"
    },
    {
        id: 2,
        title: "ReActEdge Appoints L3Harris Executive Toby Magsig as President and Interim CEO",
        date: "JANUARY 26, 2026",
        description: "COMPANY CO-FOUNDER JOSH LOSPINOSO REMAINS INVOLVED AS FOUNDER AND BOARD MEMBER",
        href: "/insights/2"
    },
    {
        id: 3,
        title: "Near-Real-Time Data Powers Faster Fault and Threat Detection",
        date: "JANUARY 21, 2026",
        description: "BOEING AND REACTEDGE JOIN FORCES TO DETECT FAULTS AND INTRUSIONS AT MISSION SPEED.",
        href: "/insights/3"
    },
    {
        id: 4,
        title: "Delivering Early-Warning for GPS Spoofing with ReActEdge's RF-Enabled Threat Detection",
        date: "JANUARY 16, 2026",
        description: "REACTEDGE BUILT AN RF-BASED DETECTION METHOD TO RAPIDLY IDENTIFY EARLY WARNING INDICATORS OF GPS SPOOFING, PROVIDING EARLIER VISIBILITY INTO NAVIGATION THREATS FOR INCREASED AWARENESS AND SAFETY.",
        href: "/insights/4"
    },
    {
        id: 5,
        title: "ReActEdge Named North American Technology Innovation Leader",
        date: "DECEMBER 23, 2025",
        description: "ANALYST FIRM RECOGNIZES REACTEDGE'S LEADERSHIP IN TRANSFORMING HIDDEN OPERATIONAL DATA INTO ACTIONABLE INSIGHTS.",
        href: "/insights/5"
    },
    {
        id: 6,
        title: "Securing Classified Data-at-Rest with ReActEdge's NIAP-Certified Software",
        date: "DECEMBER 9, 2025",
        description: "IN THE ERA OF SOFTWARE-DEFINED DEFENSE, CLASSIFIED DATA GENERATED BY DEPARTMENT OF DEFENSE WEAPONS SYSTEM PLATFORMS IS A STRATEGIC ASSET.",
        href: "/insights/6"
    },
];

export default function InsightsGrid() {
    useScrollAnimation();
    const rightRef = useRef<HTMLDivElement>(null);
    const sectionRef = useRef<HTMLDivElement>(null);

    return (
        <section
            ref={sectionRef}
            className="relative min-h-screen bg-shift-white"
        >
            <div className="sticky top-0 h-screen flex flex-col md:flex-row">
                {/* LEFT FEATURED ARTICLE */}
                <div 
                    data-animate
                    className="w-full md:w-1/2 h-1/2 md:h-full relative overflow-hidden group fade-up"
                >
                    {/* Background Image */}
                    <div className="absolute inset-0 bg-gradient-to-b from-black/50 to-black/90 transition-all duration-700 group-hover:from-black/40 group-hover:to-black/80">
                        <img
                            src="https://images.unsplash.com/photo-1540962351504-03099e0a754b?w=1200&q=80"
                            alt="F-16 Fighter Jet"
                            className="w-full h-full object-cover opacity-70 transition-all duration-700 group-hover:scale-105 group-hover:opacity-80"
                        />
                    </div>

                    {/* Content */}
                    <div className="relative h-full flex flex-col justify-end p-10 md:p-14 lg:p-20 text-white">
                        <h2 className="text-3xl md:text-4xl lg:text-5xl xl:text-6xl font-semibold leading-tight mb-8 tracking-tight transition-transform duration-500 group-hover:translate-x-2">
                            ReActEdge Awarded Key Contract for AF's Fighter of Choice, the F-16 Fighting Falcon
                        </h2>

                        <p className="text-[10px] md:text-xs font-mono tracking-[0.15em] mb-5 opacity-70 uppercase group-hover:opacity-90 transition-opacity duration-400">
                            DECEMBER 4, 2025
                        </p>

                        <p className="text-base md:text-lg mb-10 max-w-2xl opacity-80 leading-relaxed group-hover:opacity-100 transition-opacity duration-400 font-light">
                            Company selected to develop next-generation upgrades for U.S. Air Force F-16 fleet
                        </p>

                        <Link
                            href="/insights/featured"
                            className="btn-hover inline-block px-10 py-4 border-2 border-shift-blue bg-shift-blue rounded-full text-[10px] tracking-[0.2em] uppercase hover:bg-white hover:text-shift-blue hover:border-white transition-all duration-500 w-fit font-mono shadow-lg hover:shadow-2xl"
                        >
                            READ MORE
                        </Link>
                    </div>
                </div>

                {/* RIGHT SCROLLABLE GRID */}
                <div
                    ref={rightRef}
                    className="w-full md:w-1/2 h-1/2 md:h-full overflow-y-auto bg-shift-white"
                >
                    <div className="grid grid-cols-1 md:grid-cols-2">
                        {articles.map((article) => (
                            <Link
                                key={article.id}
                                data-animate
                                href={article.href}
                                className="card-container group relative bg-shift-white border border-shift-gray/30 hover:border-shift-blue p-8 md:p-10 flex flex-col justify-between min-h-[300px] md:min-h-[340px] hover:bg-white transition-all duration-500 fade-up"
                            >
                                {/* Accent Line */}
                                <div className="absolute top-0 left-0 w-0 h-[3px] bg-shift-blue group-hover:w-full transition-all duration-700"></div>
                                
                                {/* Background Gradient */}
                                <div className="absolute inset-0 bg-gradient-to-br from-white/0 to-white/50 opacity-0 group-hover:opacity-100 transition-opacity duration-500 pointer-events-none"></div>

                                <div className="relative z-10">
                                    <h3 className="text-lg md:text-xl font-medium leading-tight text-shift-dark mb-5 group-hover:text-shift-blue transition-all duration-400 tracking-tight">
                                        {article.title}
                                    </h3>
                                </div>

                                <div className="relative z-10">
                                    <p className="text-[10px] font-mono tracking-[0.12em] text-shift-dark/50 mb-4 group-hover:text-shift-dark/70 transition-colors duration-400">
                                        {article.date}
                                    </p>
                                    <p className="text-[10px] font-mono tracking-[0.08em] text-shift-dark/60 leading-relaxed uppercase group-hover:text-shift-dark/80 transition-colors duration-400">
                                        {article.description}
                                    </p>
                                </div>
                            </Link>
                        ))}
                    </div>
                </div>
            </div>
        </section>
    );
}